### ISSUE TITLE
Verkabelung

### ISSUE THREAD

**Issue by majuss** [Syralist/tcs-monitor#1]
Hi, kannst du eine grobe Anleitung dafür geben wie genau du den Arduino mit dem Bus verkabelst? Hab ich richtig verstanden, dass du einfach die 24 V auf 3,075 V mit einem Spannungsteiler runterbringst und dann direkt diesen Stromfluss untersuchst?

**Comment by Syralist** [comment]
Genau! 
Es sind im wesentlichen nur zwei Widerstände: 1MΩ und 147kΩ. Die werden in Reihe zwischen die beiden Leitungen aus der Klingel geschaltet. Damit hast du einen Spannungsteiler und kannst zwischen den beiden Widerständen das Signal für den Mikrocontroller abholen. Wichtig ist den analogen Pin und den GND Pin vor und hinter dem kleinen Widerstand anzuschließen.

**Comment by majuss** [comment]
Danke, jetzt bin ich mir sicher wie es funktioniert :)
Jetzt frage ich mich, wie ich den Code für meine Zwecke adaptieren kann, so wie ich das verstanden hab, ist die Sequenz der Länge 43 mit den 6000, 4000, 2000 ja individuell für das Signal deiner Türklingel, also müsste ich die bei mir selber aufnehmen?
Dann liest du ja auf dem Pin `A0` den analogen Wert aus, und vergleichst das einkommende Signal mit dem Sequenz Array? Und wenn alles hingehauen hat sendest du über mqtt eine Nachricht?
Was ich auch noch nicht verstanden hab, wie kannst du 3 verschiedene Zustände, also 6, 4 und 2000 überwachen?

**Comment by Syralist** [comment]
In meinem Loop lese ich den analogen Eingang und vergleiche den Wert mit einem (willkürlich gewählten) Grenzwert. Dann vergleiche ich mit dem Wert aus dem letzten Zyklus um positive und negative Flanken (Zustandswechel) zu erkennen. Bei jeder Flanke wird auf der seriellen Schnittstelle die Mikrosekunden seit der letzten Flanke ausgegeben. Das habe ich in die Tabelle kopiert und ein bisschen rumgerechnet bis ich die Sequenz in 1000 Mikrosekunden Schritten wiederholbar erkannt habe. Das habe ich in ein Array im Code geschrieben. Im Loop wird dann bei jeder Flanke die Zeit mit dem Wert aus dem Array verglichen. Wenn die Zeit übereinstimmt zähle ich den Zähler hoch, wenn am Ende alles übereingestimmt hat sende ich die Nachricht per MQTT.
