### ISSUE TITLE
Arduino JSon V5 -> V6

### ISSUE THREAD

**Issue by ansgar75** [Syralist/tcs-monitor#2]
Hi,

ich wollte am Wochenende das mal testweise aufbauen. Leider meckert Arduino (1.8.12) zwecks der Arduino JSon-Version und man soll diese Seite als Referenz nehmen für ein Upgrade: 
[https://arduinojson.org/v6/doc/upgrade/](url)

Leider bin ich damit nicht so bewandert um das entsprechend umzustellen. Kannst du dir das mal gelegentlich ansehen. Wäre Prima!!!

Danke und Grüße

**Comment by Syralist** [comment]
Hi @ansgar75,
ich habe mich da heute rangesetzt. Der Code kompiliert jetzt mit Arduino Json V6. Allerdings habe ich das nicht auf dem Mikrocontroller getestet, weil ich meine Anlage nicht zerlegen wollte ;)

**Comment by ansgar75** [comment]
Hi @Syralist,
ich habe es soweit getestet. Es lässt sich nun problemlos kompilieren und hochladen auf das Modul.
Danke dafür!!!
Nun muss ich nur noch meinen Versuchsaufbau fertigstellen ...

schöne Grüße
Ansgar
