### ISSUE TITLE
Klingelsignal an MQTT 

### ISSUE THREAD

**Issue by gee33** [Syralist/tcs-monitor#3]
Hallo Thomas, 
ich habe vor meine TCS Klingel Smart zu machen, ich habe schon den Hex code (die Adresse meiner Station z.B. 0C123450) herausgefunden ( mit dem TCS Parser Code von Aaron). Deine V3 kompiliert auch schön und findet mein mqtt broker und mein wifi. Da ich aber Homebridge und nicht homeautomator verwende kann ich dein .json nicht 1:1 übernehmen. Ich würde gerne das homebridge plugin mqttthing verwenden, dort gibt es ein Accessory names Doorbell, welches wunderbar funktioniert und sogar mit IOS14.2 den Homepod läuten lässt und im Apple TV eine notification anzeigt :-) . Dort kann ich aber keinen payload mitgeben ,sondern quasi nur "Button pressed". Auch diesen Teil habe ich am funktionieren. Was mir jetzt fehlt ist ein trigger für mqtt wenn meine Klingeladresse auf dem bus erkannt wird, kannst du mich da unterstützen ? Ich bin immer noch am lernen :-) und irgendwie bekomme ich das noch nicht hin ....
Den Türöffner habe ich auch soweit am laufen, ich kann in Homekit klicken und der ESP schaltet ein Relais , welches wiederrum den Türöffner Button für 1sec kurzschliesst, funktioniert wunderbar. Was man natürlich noch in Deinen code einbauen könnte (Luxus Lösung) : wenn in Homekit der Türöffner geklickt wird, soll der Code des Türöffners (den kenne ich mittlerweile auch z.B. 3C125678) auf den Bus geschickt werden (da hat Aaron ja auch  ein Codebeispiel), dann würde das ganze "Relaislos" funktionieren. 

schöne Grüsse 

Beispiel Klingeltaste : 
`
void loop() {
  if (!client.connected()) {
    reconnect();
  }
  if (digitalRead(Klingeltaste) == LOW) {
    Serial.println("It ringed for you!");
    client.subscribe("Klingelgedrueckt");
    client.publish("Klingelgedrueckt", "1");
    delay(1000);
`

Unterprogramm Türe öffnen : 
`
void Open() {
  //Unterprogramm Tuer oeffnen
  Serial.println("I open it for you!");
  client.publish("Haustuerstatuslaueft", "offen");
  delay(500);
  digitalWrite(Tueroeffner, `HIGH);`
  client.publish("Haustuerstatusist", "offen");
  Serial.println("Haustuer wurde geoeffnet!");
  delay(1500);
  digitalWrite(Tueroeffner, LOW);
  client.publish("Haustuerstatuslaueft", "gesichert");
  Serial.println("Haustuer wird geschlossen!");
  delay(500);
  client.publish("Haustuerstatusist", "gesichert");
  Serial.println("Haustuer wurde gesichert!");
  delay(500);
}
`

**Comment by Syralist** [comment]
Moin!
Ich kenne mich mit Homebridge nicht aus, aber wenn ich die Doku von mqttthing richtig verstehe (https://github.com/arachnetech/homebridge-mqttthing/blob/HEAD/docs/Accessories.md#doorbell), kannst du dort unter "switchValues" die payloads für Click, Double Click und LongPress festlegen. Da müsstest du die Adresse deiner Station für Click angeben können.
Den Türöffner anzusteuern per Transistor hatte ich auch überlegt, habe ich dann aber verworfen weil es keinen Mehrwert für mich bringt.

**Comment by gee33** [comment]
Hi ,
stimmt, das könnte ich versuchen. Leider bin ich aber zu doof deinen code zu verstehen ;-)  : wo machst du denn den Vergleich der Daten auf dem Bus mit der Adresse deiner Station ? 
diesen Teil verstehe ich auch nicht : 
`void sendMessage()
{
    // connectToMqtt();
    client.publish(mqtt_topic, "triggered");
    // delay(100);
    // client.disconnect();
}

//callback notifying us of the need to save config
void saveConfigCallback()
{
    Serial.println("Should save config");
    shouldSaveConfig = true;
}

void callback(char *topic, byte *payload, unsigned int length)
{
    Serial.print("Message arrived [");
    Serial.print(topic);
    Serial.print("] ");
    for (int i = 0; i < length; i++)
    {
        Serial.print((char)payload[i]);
    }
    Serial.println();
}`

Dein Code ist zwar sehr gut kommentiert , aber für einen "Anfänger" wie mich doch noch nicht ganz so klar.
Danke für ein paar insights ;-) 
G

**Comment by Syralist** [comment]
Ich mache den Vergleich auf die ID nicht auf dem Arduino. Ganz unten im Code schicke ich jede auf dem Bus erkannte Nachricht auf das MQTT Topic.
```
char byte_cmd[9];
sprintf(byte_cmd, "%08x", CMD);
client.publish(mqtt_topic, byte_cmd);
```

In CMD sind die decodierten Bytes aus der Interruptfunktion gespeichert. Dann formatiere ich das noch, damit die führenden Nullen mit übertragen werden und dann wird es gepublished.
In der JSON Datei steht drin, welche ID (bzw. Payload) in meinem Fall das Event in Home Assistant auslösen soll. Wenn ich das JSON an ein bestimmtes MQTT-Topic schicke, wird damit automatisch in Home Assistant ein entsprechendes Device angelegt.

Die Funktionen nach denen du gefragt hast sind Überreste des MQTT Beispielcodes und von V2 glaube ich. Die sind eigentlich für die Funktion nicht erforderlich.

**Comment by gee33** [comment]
mercie, verstanden. es funktioniert jetzt wie ich mir das vorstelle.
